name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    # cron every week on monday
    - cron: "0 0 * * 1"

env:
  image_name: tiangolo/nginx-rtmp
  supported_platforms: "linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: srfrnk/current-time@v1.1.0
        id: current-time
        with:
          format: YYYY-MM-DD
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkitd.toml
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          platforms: ${{ env.supported_platforms }}
          tags: "${{ env.image_name }}:latest-${{ steps.current-time.outputs.formattedTime }},${{ env.image_name }}:latest"
          push: true
